kind: Service
apiVersion: v1
metadata:
  name: philippe
spec:
  ports:
  - protocol: TCP
    port: 8008
---
kind: Endpoints
apiVersion: v1
metadata:
  name: philippe
subsets:
  - addresses:
      #- ip: 10.0.1.1
      - ip: 2a01:4f9:2a:25d5::17
    ports:
      - port: 8008
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: philippe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/issuer: letsencrypt-prod
spec:
  rules:
  - host: philippe.paxpar.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: philippe
            port:
              number: 8008
  - host: philippe.qdoc.pro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: philippe
            port:
              number: 8008
  tls:
  - hosts:
    - philippe.paxpar.tech
    - philippe.qdoc.pro
    secretName: paxpar-tls
---
#TODO: move to apiVersion: cert-manager.io/v1
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  labels:
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: info@paxpar.tech
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
---
#TODO: move to apiVersion: cert-manager.io/v1
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
  labels:
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: info@paxpar.tech
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
